---
- name: Configure Border Handoff on Cisco Devices
  hosts: border_leaf
  gather_facts: no
  connection: network_cli

  vars_files:
    - ./vars/vrf_lite.yml

  tasks:

    - name: Validate BGP ASN
      assert:
        that:
          - bgp.asn is defined
          - bgp.asn | int > 0
          - bgp.asn | int < 65536
        fail_msg: "Invalid or missing BGP ASN"
        success_msg: "BGP ASN is valid"

    - name: Validate border interface definitions
      assert:
        that:
          - border_interfaces | length > 0
          - border_interfaces | selectattr('name', 'defined') | list | length == border_interfaces | length
          - border_interfaces | selectattr('vlan_id', 'defined') | list | length == border_interfaces | length
          - border_interfaces | selectattr('vrf', 'defined') | list | length == border_interfaces | length
        fail_msg: "Missing required interface attributes (name, vlan_id, vrf)"
        success_msg: "All interfaces are properly defined"

    - name: Validate IPv4 address fields
      assert:
        that:
          - item.ipv4.address is match("^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")
          - item.ipv4.mask is match("^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")
        fail_msg: "Invalid IPv4 address or mask on {{ item.name }}"
        success_msg: "IPv4 config for {{ item.name }} is valid"
      loop: "{{ border_interfaces }}"

    - name: Validate IPv6 address fields
      assert:
        that:
          - item.ipv6.address is match("^[0-9a-fA-F:]+$")
          - item.ipv6.prefix | int >= 1
          - item.ipv6.prefix | int <= 128
        fail_msg: "Invalid IPv6 configuration on {{ item.name }}"
        success_msg: "IPv6 config for {{ item.name }} is valid"
      loop: "{{ border_interfaces }}"

    - name: Validate BGP address families
      assert:
        that:
          - bgp.address_families | length > 0
          - bgp.address_families | selectattr('vrf', 'defined') | list | length == bgp.address_families | length
          - bgp.address_families | selectattr('type', 'defined') | list | length == bgp.address_families | length
        fail_msg: "Invalid or missing BGP address-family definitions"
        success_msg: "All BGP address-family entries are valid"

    - name: Render border handoff configuration
      template:
        src: ./jinja_templates/bgp_vrf_lite.j2
        dest: configs/border_handoff_{{ inventory_hostname }}.cfg

    - name: Push border handoff configuration to device
      ios_config:
        src: configs/border_handoff_{{ inventory_hostname }}.cfg
        save_when: modified
