---
# Global fabric BGP EVPN VxLAN parameters
asn: 1001
peer_policy:
  leaf: leaf_peer_policy_template
  spine: spine_peer_policy_template
  border: border_peer_policy_template
peer_session:
  leaf: leaf_peer_session_template
  spine: spine_peer_session_template
  border: border_peer_session_template
router_id_interface: Loopback0
update_source: Loopback0
source_interface: Loopback0
peer_groups:
  # Each device refers to neighbors by name so we can resolve IP automatically
  leaf: []  # leaves will peer with spines (populated dynamically if needed)
  spine: [] # spines will peer with leaves, borders and other spines (populated dynamically if needed)
  border: [] # borders will peer with spines (populated dynamically if needed)
proj_name: BGP_EVPN_FABRIC_AUTOGEN
soft_type: IOS-XE
state: merged
language: JINJA
product_family: Switches and Hubs

# Device inventory grouped by role
fabric_devices:
  spine:  # only one spine group typically
    - group_name: spine-group
      devices:
        - device_name: evpn-app-c9k-29
          mgmt_ip: 172.27.248.81
          mac_address: 00:0c:29:a1:bd:78
          username: admin
          password: Admin@123
          enable_pwd: Lablab123!
          loopback_ip: 99.1.1.1
          neighbors:
            - 99.3.3.3
            - 99.4.4.4
  border:  # multiple border groups allowed
    - group_name: border-group1
      devices:
        - device_name: evpn-app-c9k-30
          mgmt_ip: 172.27.248.82
          mac_address: 00:0c:29:c9:ee:a0
          username: admin
          password: Admin@123
          enable_pwd: Lablab123!
          loopback_ip: 99.3.3.3
          neighbors:
            - 99.1.1.1
  leaf:  # multiple leaf groups allowed
    - group_name: leaf-group1
      devices:
        - device_name: evpn-app-c9k-31
          mgmt_ip: 172.27.248.83
          mac_address: 00:50:56:be:98:20
          username: admin
          password: Admin@123
          enable_pwd: Lablab123!
          loopback_ip: 99.4.4.4
          neighbors:
            - 99.1.1.1

# Mapping role to template path
role_template_map:
  leaf: ./jinja_templates/bgp_evpn_fabric_leaf_cli.j2
  spine: ./jinja_templates/bgp_evpn_fabric_spine_cli.j2
  border: ./jinja_templates/bgp_evpn_fabric_border_cli.j2
  leaf_delete: ./jinja_templates/bgp_evpn_fabric_leaf_delete_cli.j2
  spine_delete: ./jinja_templates/bgp_evpn_fabric_spine_delete_cli.j2
  border_delete: ./jinja_templates/bgp_evpn_fabric_border_delete_cli.j2
